### ISSUE TITLE
Typo3 Database Analysator don't find special tables

### ISSUE THREAD

**Issue by humberg** [aimeos/aimeos-typo3#1]
Hi,

when I start the typo3 Database Analyser, he give me the information, that all special tables from aimeos are not valid - so he attemts to delete them ...

I think (I'm not the big Typo3 developer) in the /ext/aimeos/ext_tables.sql  have to notice all aimeos tables, or?

**Comment by aimeos** [comment]
This is a commonly known issue but not a problem as long as you don't let the database analyzer delete the tables.
They haven't been added to the ext_tables.sql because the core library uses a more sophisticated way of managing the tables. It would be painful to keep all table definitions twice and in sync, especially as Aimeos extensions can create own tables as well.

**Comment by aimeos** [comment]
A ticket at the TYPO3 forge site to fix this already exists: https://forge.typo3.org/issues/33136
