### ISSUE TITLE
Can't choose from full currency list

### ISSUE THREAD

**Issue by joakim1** [aimeos/aimeos-typo3#10]
Screenshot: http://prntscr.com/au3i0l

Can only choose from top currencies sorted alphabetically.

**Comment by aimeos** [comment]
The parameters to limit and sort the languages/currencies in the drop-down haven't been transfered correctly due to a strange behavior of the initializeAction() method in the Jsonadm controller.

This version should solve the problem: https://aimeos.org/fileadmin/download/aimeos_16.4.2-pre3.zip
Can you confirm?

**Comment by joakim1** [comment]
http://prntscr.com/auaqfk - I can now choose currencies that I have enabled. Thanks for the assistance.
