### ISSUE TITLE
2017.02 Scheduler Email broken

### ISSUE THREAD

**Issue by gilbertsoft** [aimeos/aimeos-typo3#31]
Since the new update the scheduler for emails is broken. I get the following message at the scheduler:

Die Ausführung von Task "Planer für Aimeos Shop E-Mails (aimeos)" ist fehlgeschlagen mit folgender Meldung: PHP Warning: Creating default object from empty value in /var/www/clients/client15/web7/private/typo3_src-7.6.15/typo3/sysext/core/Classes/TypoScript/TemplateService.php line 538

I compared the 2 versions at github but unfortunately I was not able to find the bug quickly because it has too much changed at the scheduler source code and at the logs was nothing to find ;-(

A downgrade to 2017.01 solved the problem.

**Comment by aimeos** [comment]
Doesn't send the e-mail scheduler any e-mails at all?

The problem was the TSFE initialization. The TypoScriptService called in `getConfigArray()` requires the TSFE and tries to access it using `$GLOBALS['TSFE']` which wasn't there yet.

This is fixed with this commit: https://github.com/aimeos/aimeos-typo3/commit/e7e0c6d7f04fd7605069dadc9d75daed51b85498

**Comment by gilbertsoft** [comment]
It did nothing I think, only the message submitted before I saw. No other logs not on filesystem and nothing in the db.

I didn't find the time to test this, I have to go forward with the version 2017.01plus some own additions because the shop has to go online now. Google already indexed it and my customer get a call today that something did go wrong in the shop :-( I already prepared a copy of it for future developpment and there I will install the newest sources after launch of the production system... I hope will be this night :-D
