### ISSUE TITLE
[FEATURE] add cachable Catalog -> list plugin

### ISSUE THREAD

**Issue by AndreasA** [aimeos/aimeos-typo3#66]
In my aimeos Frontend my shop doesn't use any filter / sort or pagination for the products per category.
It would be nice for those lists to be cachable as they don't change content and the availability state is loaded via Javascript anyway.
I think a second plugin that is "cachable" might be the best solution, then one can define per page.
The plugin is cached anyway but that way it would be cached by TYPO3 too and could be part of the page cache.

Actually, if you are using TYPO3 linkbuilder for sorting / pagination links than it should also be cachable for those links as it should add a correct cHash. 
The only thing then that would require the uncachable plugin would be a search funktion.

**Comment by aimeos** [comment]
Yes, the output of the catalog list plugin is cached by the TYPO3 caching framework.

If you want that content to be part of the full page cache, your own extension can define a cachable plugin version by adding these lines (use own name instead of 'catalog-list') and leaving the second last array() empty:
https://github.com/aimeos/aimeos-typo3/blob/master/ext_localconf.php#L63

That one needs to be copied to in your own extension with a new name:
https://github.com/aimeos/aimeos-typo3/blob/master/ext_tables.php#L79

**Comment by AndreasA** [comment]
Yes, I know I can do so but it would be nice to have the option out-of-the-box for a full page cache plugin.
On another note:
https://github.com/aimeos/aimeos-typo3/blob/master/ext_tables.php#L79
```
$TCA['tt_content']['types']['list']['subtypes_addlist'][$pluginName . '_catalog-stock'] = 'pi_flexform';
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPiFlexFormValue( $pluginName . '_catalog-stock', 'FILE:EXT:' . $_EXTKEY . '/Configuration/FlexForms/CatalogStock.xml' );
\TYPO3\CMS\Extbase\Utility\ExtensionUtility::registerPlugin( 'Aimeos.' . $_EXTKEY, 'catalog-stock', 'Aimeos Shop - Catalog stock JSON' );
```

Those lines should preferable be placed in Configuration/TCA/Overrides/tt_content.php
And for addStaticFile it should be Configuration/TCA/Overrides/tt_content.php

See also: https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.5/Breaking-78384-FrontendIgnoresTCAInExtTables.html
or also
https://docs.typo3.org/typo3cms/ExtbaseFluidBook/b-ExtbaseReference/Index.html

**Comment by aimeos** [comment]
cHash ist difficult and doesn't work with in many cases. It's switched off for all Aimeos plugins because in basket and checkout it must not be used at all and the catalog plugins can also depend on user group and session values.

Thanks for your hint regarding registration. Can you double check if it's correct now?
https://github.com/aimeos/aimeos-typo3/commit/bce5262d3646e831e6f88bf858de6e579c24afd8

**Comment by AndreasA** [comment]
Hi regarding cHash. You are right with user session and so on. Also as you mentioned aimeos itself already has good caching, so it isn't really necessary anyway.
And for the list plugin I can just create my own if I am sure, that list can be cachable. Will have to test if everything works correctly then but it should as it will only be used to output the "current" content.

Regarding change it looks good at a first glance but i will have to test it.
Also: you also "fixed" an upcoming issue in future versions regarding $_EXTKEY and ext_localconf.php:
https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Important-82692-GuidelinesForExtensionFiles.html
However, in ext_tables.php $_EXTKEY still needs to be replaced.
An idea regarding this might be to do something like this - in case you ever want to rename the extension:

```
call_user_func(function ($extKey) {
 \TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
	'Aimeos.' . $extKey,
 	'basket-small',	 	'basket-small',
 	array( 'Basket' => 'small' ),	 	array( 'Basket' => 'small' ),
 	array( 'Basket' => 'small' )	 	array( 'Basket' => 'small' )
 );	 );
}, 'aimeos');
```

**Comment by aimeos** [comment]
OK, $_EXTKEY is now gone too: https://github.com/aimeos/aimeos-typo3/commit/be080b0215d6c1fcdfd2319c3edf7e1143009f3d
