### ISSUE TITLE
Remove superfluous autoloading

### ISSUE THREAD

**Issue by andreasfernandez** [aimeos/aimeos-typo3#8]
Currently, ext_localconf.php requires Resources/Libraries/autoload.php. The same autoload definition is catched by TYPO3's composer autoloader and placed in typo3temp/autoload.

Please remove the `require` call as it's superfluous and also makes class overriding impossible.

**Comment by aimeos** [comment]
The TYPO3 autoloader mechanism is rather new (7.4 IIRC) and removing the line would break all versions before including 6.2 LTS. What class do you want to override?

**Comment by andreasfernandez** [comment]
I want to override Aimeos\Client\Html\Catalog\Detail\Standard because I have to add a very special feature: Some products should not offer the price and the "add to basket" button but show some text until the user has a valid fe_user session.

**Comment by aimeos** [comment]
We are not recommend using dev-master for real projects at the moment since we are making all changes for the upcoming 3.0 series now that would have broken BC in the past. Furthermore, the documentation and infrastructure aren't updated yet which will create a lot of frustration on your side for sure ;-)

Overriding an Aimeos implementation works this way: Create a new TYPO3 extension (https://aimeos.org/developer/extensions/) for 2.4 which already contains an Aimeos extension and the necessary environment. Information about the details behind can be found here: https://aimeos.org/docs/TYPO3/Extend_Aimeos

**Extend** the class you want to change (give it a new name!) and overwrite the method you need. Then configure your new class to be used in Resources/Private/Config/ of your new TYPO3 extension. The setting that influences the used class is "https://aimeos.org/docs/Configuration/Core/client/html/catalog/detail/name" (or the "name" setting of one of the sub-clients if you need to extend one of these instead). The description of the same solution but for another class is described here: https://aimeos.org/help/help-f15/changing-product-email-display-t503.html#p1990

**Comment by andreasfernandez** [comment]
Thank you, I will try it that way.

**Comment by andreasfernandez** [comment]
If I debugged it right, the method that uses this config is `\Aimeos\Client\Html\Catalog\Detail\Factory::createClient()`, passing the class name as 3rd parameter. This method is called once in `Aimeos\Aimeos\Controller\CatalogController`, but the `$name` param is not passed, thus being null and my config is not taken into account.

I create a file `client.php` in Resources/Private/Config and return an array as described int the linked thread. Did I do something wrong here?

**Comment by andreasfernandez** [comment]
Alright, I found the issue in my client.php: I must omit the top level of the configuration, the file name itself reflects the top level already.

This works:
    return array(
        'html' =>  array(
            'catalog' => array(
                'detail' => array(
                    'name' => 'Custom'
                )
            )
        )
    );
