### ISSUE TITLE
[QUESTION] E-Mail Task - link to URLs with the correct language?

### ISSUE THREAD

**Issue by AndreasA** [aimeos/aimeos-typo3#89]
I adopted the mail templates to include some further links to TYPO3 pages (using the URL helper) and they work fine. However, I noticed that when using any language but the default language, the URLs still point to the default language.
I don't have product detail pages on that website, so I am not sure about the detail product links (removed those).
Just wondering is there an easy way to change this behaviour?

**Comment by aimeos** [comment]
You have to hand over the "L" parameter in the list of parameters for TYPO3. Aimeos passes parameters for "site", "locale" and "currency" but the "locale" parameter is not recognized by TYPO3 as language. Another problem is that TYPO3 is expecting the sys_language_id instead of the ISO language code.

**Comment by AndreasA** [comment]
Yes, but wouldn't a similar issue be with the detail product page links in the scheduler task? Also I could be wrong but I think with TYPO3 v9 the have started to improve the language handling, e.g. by adding ISO-Codes to the languages etc.

However, wouldn't a mapping of aimeos language code to TYPO3 langauge ID be enough and instantiate the default language parameter with the corresponding language ID?

**Comment by aimeos** [comment]
Yes, the detail page links will be also affected because they doesn't contain the "L" parameter. Don't know if and how TYPO3 9 changed language handling but it's also possible to use L=de for example and map that via TypoScript conditions to sys_language_uid=1

**Comment by aimeos** [comment]
In the next version, the ISO language code (e.g. "de") will be assigned to the "L" parameter. If you use the language codes instead of the "sys_language_uid" value and map the language code back to the "sys_language_uid" via TypoScript, then you will be able to create URLs with will point to the translated page.
